export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const INVOICE_SERVICE = Symbol('INVOICE_SERVICE');
export const INVOICE_EVENT_PUBLISHER = Symbol('INVOICE_EVENT_PUBLISHER');
export const SEND_INVOICE_SAGA_COORDINATOR = Symbol('SEND_INVOICE_SAGA_COORDINATOR');
